# Generated by Django 4.2 on 2023-04-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('program_id', models.IntegerField()),
                ('student_no', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('birthdate', models.DateField()),
                ('active_deactive', models.CharField(max_length=50)),
                ('access_type', models.IntegerField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
