# Generated by Django 4.2 on 2023-04-25 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='employment_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
