# Generated by Django 4.2 on 2023-04-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0002_students_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
