# Generated by Django 4.2 on 2023-04-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0008_alter_students_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
