# Generated by Django 4.2 on 2023-05-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0013_auto_20230501_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='access_type',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
