# Generated by Django 4.2 on 2023-05-15 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0014_alter_students_access_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='files')),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('program_code', models.CharField(max_length=50)),
                ('program_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='course_enrollment',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='course_enrollment',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course_enrollment',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='course_enrollment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course_enrollment',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.instructor_auth'),
        ),
        migrations.AlterField(
            model_name='course_enrollment',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Student_Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Ongoing', max_length=10)),
                ('grades', models.CharField(max_length=3)),
                ('date_enrolled', models.DateTimeField()),
                ('course_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.course_enrollment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.students_auth')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('course_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.course_enrollment')),
            ],
        ),
        migrations.AlterField(
            model_name='students_auth',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.program'),
        ),
    ]
