# Generated by Django 4.2 on 2023-05-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0015_csv_program_course_enrollment_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_start_date', models.DateField(blank=True, null=True)),
                ('old_end_date', models.DateField(blank=True, null=True)),
                ('old_start_time', models.TimeField(blank=True, null=True)),
                ('old_end_time', models.TimeField(blank=True, null=True)),
                ('new_start_date', models.DateField(blank=True, null=True)),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('course_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.course_enrollment')),
            ],
        ),
    ]
