# Generated by Django 4.2 on 2023-05-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0016_change_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_schedule',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
