# Generated by Django 4.2 on 2023-05-16 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0020_change_schedule_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_schedule',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
