# Generated by Django 4.2 on 2023-05-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0016_alter_student_enrollment_status'),
        ('sitlms_app', '0021_alter_change_schedule_request_date'),
    ]

    operations = [
    ]
