# Generated by Django 4.2 on 2023-05-23 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitlms_app', '0022_merge_20230517_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.CharField(max_length=10000, null=True)),
                ('address', models.CharField(max_length=10000, null=True)),
                ('user_contact_no', models.CharField(max_length=255, null=True)),
                ('emergency_contact', models.CharField(max_length=255, null=True)),
                ('emergency_contact_no', models.CharField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='student_pic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
