# Generated by Django 4.2 on 2023-05-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0023_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructor_auth',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students_auth',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
