# Generated by Django 4.2 on 2023-05-30 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0024_alter_admin_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_firstname', models.CharField()),
                ('sender_lastname', models.CharField()),
                ('sender_access_type', models.IntegerField()),
                ('sender_subject', models.CharField()),
                ('sender_message', models.CharField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 5, 30, 11, 8, 33, 771752))),
            ],
        ),
    ]
