# Generated by Django 4.2 on 2023-05-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0028_alter_submitissue_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_enrollment',
            name='course_batch',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student_enrollment',
            name='date_enrolled',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='students_auth',
            name='active_deactive',
            field=models.BooleanField(default=True),
        ),
    ]
