# Generated by Django 4.2 on 2023-05-15 03:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitlms_app', '0015_csv_program_course_enrollment_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.instructor_auth')),
                ('course_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.course_enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(max_length=255)),
                ('activity_desc', models.CharField(max_length=1000)),
                ('activity_attachment', models.URLField()),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('deadline', models.DateTimeField()),
                ('grading_percentage', models.IntegerField()),
                ('course_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.course_enrollment')),
            ],
        ),
    ]
