# Generated by Django 4.2 on 2023-05-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_activity',
            name='activity_attachment',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course_activity',
            name='grading_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
