# Generated by Django 4.2 on 2023-05-17 06:10

import apps.sitlms_instructor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitlms_instructor', '0002_alter_course_activity_activity_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_activity',
            name='max_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_activity',
            name='activity_attachment',
            field=models.FileField(blank=True, upload_to=apps.sitlms_instructor.models.activity_attachment_path),
        ),
        migrations.AlterField(
            model_name='course_activity',
            name='grading_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='Activity_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('course_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_instructor.course_activity')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
