# Generated by Django 4.2 on 2023-05-30 02:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_app', '0024_alter_admin_middle_name_and_more'),
        ('sitlms_instructor', '0004_alter_course_activity_activity_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_comments',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ActivityPrivateComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_instructor.course_activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitlms_app.students_auth')),
            ],
        ),
    ]
