# Generated by Django 4.2 on 2023-05-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitlms_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_submission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
